### ISSUE TITLE
缺少news-backward-0.4.1.pt

### ISSUE THREAD

**Issue by GekiKaraa** [Das-Boot/scite#10]
你好，在Create Contextual String Embeddings with Flair的步骤中，如下代码
charlm_embedding_backward = FlairEmbeddings('your path to /news-backward-0.4.1.pt')
在我的本地路径中是一个空文件，请问还有哪里可以下载到这个文件呢

**Comment by RinForFuture** [comment]
![1](https://user-images.githubusercontent.com/58875869/149607703-27e7821e-edb7-4317-86cf-af45c9cdde59.png)
将代码改成如图所示即可自动联网下载所需文件。

**Comment by GekiKaraa** [comment]
> ![1](https://user-images.githubusercontent.com/58875869/149607703-27e7821e-edb7-4317-86cf-af45c9cdde59.png) 将代码改成如图所示即可自动联网下载所需文件。

谢谢！我在虚拟环境的路径底下也找到了这个文件 问题已经解决
