### ISSUE TITLE
希望能了解到拓展语料集的标注规范: )

### ISSUE THREAD

**Issue by ArrogantL** [Das-Boot/scite#3]
论文中提到了文中使用的语料是对 semeval 2010 task 8 的拓展，希望能了解到你们标注的 准则是怎样的。感谢！

**Comment by Das-Boot** [comment]
抱歉这么久才回复，就是扩展了原标注，具体可以看语料
![Screen Shot 2020-06-18 at 8 45 01 AM](https://user-images.githubusercontent.com/25773391/84964926-0e0d5700-b140-11ea-9c5b-35dcc4702a56.png)

**Comment by Das-Boot** [comment]
抱歉这么久才回复，就是扩展了原标注，具体可以看语料
![Screen Shot 2020-06-18 at 8 45 01 AM](https://user-images.githubusercontent.com/25773391/84964977-3c8b3200-b140-11ea-87f3-aa2cd9a5e291.png)

**Comment by Das-Boot** [comment]
抱歉这么久才回复，就是扩展了原标注（“In the original dataset, only one causal triplet in each sentence was annotated. We extend the annotation with the causal triplets not considered by the SemEval annotators; for example, we annotate all of the causal triplets in the sentence in Fig. 2 (more examples are shown in Fig. 3, Fig. 5 and Fig. 6).”），具体可以看已公开的语料。
