### ISSUE TITLE
您好，你的代码提供的的数据不全，可以提供一下吗，index_w.pkl，extvec_embedding.npy谢谢 

### ISSUE THREAD

**Issue by liangliang-max** [Das-Boot/scite#7]
您好，你的代码提供的的数据不全，可以提供一下吗，index_w.pkl，extvec_embedding.npy谢谢 
class Data:
    def __init__(self, args):
        self.word2index, self.index2word = pickle.load(
            open(args.file_path+'index/index_w.pkl', 'rb'))
        self.embedding = np.load(
            open(args.file_path+'embedding/extvec_embedding.npy', 'rb'))

**Comment by Das-Boot** [comment]
[Archive.zip](https://github.com/Das-Boot/scite/files/6278365/Archive.zip)
Thanks for your interest! 其实index_w.pkl，extvec_embedding.npy均可由数据处理代码生成

**Comment by liangliang-max** [comment]
好的，谢谢您解答


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Das-Boot/scite"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年4月8日(星期四) 晚上7:52
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Das-Boot/scite] 您好，你的代码提供的的数据不全，可以提供一下吗，index_w.pkl，extvec_embedding.npy谢谢  (#7)





 
Archive.zip
 Thanks for your interest! 其实index_w.pkl，extvec_embedding.npy均可由数据处理代码生成
